# Generated by Django 5.1.15 on 2026-05-10 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='mediarendition',
            name='is_playable',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='MediaDerivative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('thumbnail', 'Thumbnail'), ('waveform', 'Waveform'), ('preview', 'Preview')], max_length=24)),
                ('storage_key', models.CharField(max_length=512)),
                ('format', models.CharField(max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=24)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derivatives', to='media.mediaasset')),
            ],
            options={
                'indexes': [models.Index(fields=['asset', 'kind', 'status'], name='media_media_asset_i_34df83_idx')],
            },
        ),
        migrations.CreateModel(
            name='MediaProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('ingest', 'Ingest'), ('transcode', 'Transcode'), ('thumbnail', 'Thumbnail'), ('waveform', 'Waveform')], max_length=24)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=24)),
                ('celery_task_id', models.CharField(blank=True, max_length=120)),
                ('log', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='media.mediaasset')),
            ],
            options={
                'indexes': [models.Index(fields=['kind', 'status', 'created_at'], name='media_media_kind_a6f1f2_idx')],
            },
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=24)),
                ('upload_url', models.URLField(blank=True, max_length=1200)),
                ('expires_at', models.DateTimeField()),
                ('expected_checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('expected_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upload_session', to='media.mediaasset')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'expires_at'], name='media_uploa_status_c11089_idx')],
            },
        ),
    ]
