# Generated by Django 5.1.15 on 2026-05-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visibility', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private'), ('archived', 'Archived')], default='draft', max_length=24)),
                ('title', models.CharField(max_length=260)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('summary', models.TextField()),
                ('editorial_notes', models.TextField(blank=True)),
                ('contributor_notes', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=260)),
                ('source_type', models.CharField(choices=[('interview', 'Interview'), ('book', 'Book'), ('field_recording', 'Field recording'), ('website', 'Website'), ('manuscript', 'Manuscript')], max_length=32)),
                ('author', models.CharField(blank=True, max_length=180)),
                ('published_at', models.CharField(blank=True, max_length=80)),
                ('url', models.URLField(blank=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProvenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=80)),
                ('source_name', models.CharField(blank=True, max_length=180)),
                ('source_url', models.URLField(blank=True)),
                ('source_identifier', models.CharField(blank=True, max_length=180)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='SourceRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('editorial', 'Editorial'), ('community', 'Community')], max_length=24)),
                ('value', models.PositiveSmallIntegerField(default=0)),
                ('max_value', models.PositiveSmallIntegerField(default=5)),
                ('rationale', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VocabularyTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vocabulary', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=120)),
                ('label', models.CharField(max_length=180)),
                ('uri', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['vocabulary', 'label'],
            },
        ),
    ]
