# Generated by Django 5.1.15 on 2026-05-10 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archive', '0001_initial'),
        ('catalog', '0001_initial'),
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='archiverecord',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='archive_records', to='catalog.collection'),
        ),
        migrations.AddField(
            model_name='archiverecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archiverecord',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='archive_records', to='catalog.person'),
        ),
        migrations.AddField(
            model_name='archiverecord',
            name='tracks',
            field=models.ManyToManyField(blank=True, related_name='archive_records', to='catalog.track'),
        ),
        migrations.AddField(
            model_name='archiverecord',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archiverecord',
            name='citations',
            field=models.ManyToManyField(blank=True, related_name='archive_records', to='archive.citation'),
        ),
        migrations.AddField(
            model_name='provenancerecord',
            name='archive_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provenance_records', to='archive.archiverecord'),
        ),
        migrations.AddField(
            model_name='provenancerecord',
            name='media_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provenance_records', to='media.mediaasset'),
        ),
        migrations.AddField(
            model_name='sourcerating',
            name='archive_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_ratings', to='archive.archiverecord'),
        ),
        migrations.AddField(
            model_name='sourcerating',
            name='contributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='vocabularyterm',
            constraint=models.UniqueConstraint(fields=('vocabulary', 'code'), name='unique_vocabulary_code'),
        ),
        migrations.AddField(
            model_name='archiverecord',
            name='terms',
            field=models.ManyToManyField(blank=True, related_name='archive_records', to='archive.vocabularyterm'),
        ),
        migrations.AddIndex(
            model_name='provenancerecord',
            index=models.Index(fields=['event_type', 'created_at'], name='archive_pro_event_t_c7bfc2_idx'),
        ),
        migrations.AddIndex(
            model_name='archiverecord',
            index=models.Index(fields=['visibility'], name='archive_arc_visibil_30029e_idx'),
        ),
    ]
