# Generated by Django 5.1.15 on 2026-05-13 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('dervaish_prototype', 'Dervaish prototype'), ('mediacms', 'MediaCMS'), ('omeka_s', 'Omeka S')], max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('dry_run', 'Dry run'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=24)),
                ('dry_run', models.BooleanField(default=True)),
                ('source_label', models.CharField(blank=True, max_length=180)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source', 'status', 'created_at'], name='imports_imp_source_e6a480_idx')],
            },
        ),
    ]
