# Generated by Django 5.2.15 on 2026-06-21 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenditionVerseTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_ms', models.PositiveIntegerField()),
                ('end_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('rendition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verse_timings', to='catalog.rendition')),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timings', to='catalog.verse')),
            ],
            options={
                'ordering': ['rendition', 'start_ms'],
                'constraints': [models.UniqueConstraint(fields=('rendition', 'verse'), name='unique_rendition_verse_timing')],
            },
        ),
    ]
