# Generated by Django 5.2.15 on 2026-06-21 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video'), ('image', 'Image')], max_length=8)),
                ('storage_key', models.CharField(blank=True, max_length=512)),
                ('source_url', models.URLField(blank=True, max_length=1024)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('source_name', models.CharField(blank=True, max_length=200)),
                ('original_filename', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Caption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language_code', models.CharField(max_length=16)),
                ('fmt', models.CharField(default='vtt', max_length=10)),
                ('storage_key', models.CharField(blank=True, max_length=512)),
                ('url', models.URLField(blank=True, max_length=1024)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captions', to='media.mediaasset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaRendition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('container', models.CharField(max_length=16)),
                ('bitrate_kbps', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('codec', models.CharField(blank=True, max_length=40)),
                ('storage_key', models.CharField(blank=True, max_length=512)),
                ('url', models.URLField(blank=True, max_length=1024)),
                ('is_streaming', models.BooleanField(default=True)),
                ('is_offline_download', models.BooleanField(default=False)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='ready', max_length=12)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='media.mediaasset')),
            ],
            options={
                'ordering': ['container', 'bitrate_kbps'],
            },
        ),
    ]
