# Generated by Django 5.2.15 on 2026-06-21 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visibility', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending review'), ('public', 'Public'), ('unlisted', 'Unlisted'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=16)),
                ('editorial_notes', models.TextField(blank=True)),
                ('title', models.CharField(max_length=240)),
                ('slug', models.SlugField(max_length=260, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_curated', models.BooleanField(default=False)),
                ('share_token', models.CharField(blank=True, max_length=80)),
                ('artwork', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_artwork', to='media.mediaasset')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visibility', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending review'), ('public', 'Public'), ('unlisted', 'Unlisted'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=16)),
                ('editorial_notes', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('name_native', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('biography', models.TextField(blank=True)),
                ('era', models.CharField(blank=True, max_length=120)),
                ('region', models.CharField(blank=True, max_length=160)),
                ('external_ids', models.JSONField(blank=True, default=dict)),
                ('portrait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portrait_of', to='media.mediaasset')),
                ('tradition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='taxonomy.vocabularyterm')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Kalam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visibility', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending review'), ('public', 'Public'), ('unlisted', 'Unlisted'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=16)),
                ('editorial_notes', models.TextField(blank=True)),
                ('title', models.CharField(max_length=260)),
                ('title_native', models.CharField(blank=True, max_length=260)),
                ('title_transliterated', models.CharField(blank=True, max_length=260)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('era', models.CharField(blank=True, max_length=120)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('genre', models.ForeignKey(blank=True, limit_choices_to={'kind': 'genre'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kalams_genre', to='taxonomy.vocabularyterm')),
                ('primary_language', models.ForeignKey(blank=True, limit_choices_to={'kind': 'language'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kalams_primary', to='taxonomy.vocabularyterm')),
                ('themes', models.ManyToManyField(blank=True, limit_choices_to={'kind': 'theme'}, related_name='kalams_themed', to='taxonomy.vocabularyterm')),
                ('tradition', models.ForeignKey(blank=True, limit_choices_to={'kind': 'tradition'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kalams_tradition', to='taxonomy.vocabularyterm')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_kalams', to='catalog.person')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Rendition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visibility', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending review'), ('public', 'Public'), ('unlisted', 'Unlisted'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=16)),
                ('editorial_notes', models.TextField(blank=True)),
                ('title', models.CharField(blank=True, max_length=260)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('album', models.CharField(blank=True, max_length=240)),
                ('publisher', models.CharField(blank=True, max_length=240)),
                ('style', models.CharField(blank=True, max_length=240)),
                ('protection_level', models.CharField(choices=[('open', 'Open (public CDN, app-private offline)'), ('signed', 'Signed/expiring URLs'), ('drm', 'Platform DRM')], default='open', max_length=8)),
                ('rights_note', models.CharField(blank=True, max_length=300)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('kalam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renditions', to='catalog.kalam')),
                ('media_assets', models.ManyToManyField(blank=True, related_name='renditions', to='media.mediaasset')),
            ],
            options={
                'ordering': ['kalam', 'year'],
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('author', 'Author / poet'), ('reciter', 'Reciter / voice artist'), ('composer', 'Composer'), ('translator', 'Translator'), ('contributor', 'Contributor')], max_length=16)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('kalam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='catalog.kalam')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='catalog.person')),
                ('rendition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='catalog.rendition')),
            ],
            options={
                'ordering': ['display_order', 'person__name'],
            },
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.collection')),
                ('rendition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.rendition')),
            ],
            options={
                'ordering': ['collection', 'position'],
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='renditions',
            field=models.ManyToManyField(related_name='collections', through='catalog.CollectionItem', to='catalog.rendition'),
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('text_native', models.TextField(blank=True)),
                ('transliteration', models.TextField(blank=True)),
                ('translations', models.JSONField(blank=True, default=dict)),
                ('meaning', models.JSONField(blank=True, default=dict)),
                ('kalam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='catalog.kalam')),
            ],
            options={
                'ordering': ['kalam', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='kalam',
            index=models.Index(fields=['visibility', 'published_at'], name='catalog_kal_visibil_95dbb9_idx'),
        ),
        migrations.AddIndex(
            model_name='rendition',
            index=models.Index(fields=['visibility', 'published_at'], name='catalog_ren_visibil_282f34_idx'),
        ),
        migrations.AddConstraint(
            model_name='collectionitem',
            constraint=models.UniqueConstraint(fields=('collection', 'rendition'), name='unique_collection_rendition'),
        ),
        migrations.AddConstraint(
            model_name='verse',
            constraint=models.UniqueConstraint(fields=('kalam', 'order'), name='unique_verse_order'),
        ),
    ]
