# Generated by Django 5.1.15 on 2026-05-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visibility', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private'), ('archived', 'Archived')], default='draft', max_length=24)),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(max_length=240, unique=True)),
                ('is_curated', models.BooleanField(default=False)),
                ('share_token', models.CharField(blank=True, max_length=80, unique=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visibility', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private'), ('archived', 'Archived')], default='draft', max_length=24)),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('primary_role', models.CharField(choices=[('reciter', 'Reciter'), ('writer', 'Writer'), ('translator', 'Translator'), ('contributor', 'Contributor')], default='contributor', max_length=32)),
                ('biography', models.TextField(blank=True)),
                ('origin', models.CharField(blank=True, max_length=160)),
                ('external_ids', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['queue', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visibility', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private'), ('archived', 'Archived')], default='draft', max_length=24)),
                ('title', models.CharField(max_length=240)),
                ('slug', models.SlugField(max_length=260, unique=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('primary_language_code', models.CharField(default='ur', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TrackCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('reciter', 'Reciter'), ('writer', 'Writer'), ('translator', 'Translator'), ('contributor', 'Contributor')], max_length=32)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=240)),
            ],
            options={
                'ordering': ['track', 'display_order', 'person__name'],
            },
        ),
        migrations.CreateModel(
            name='TrackVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
