# Generated by Django 5.1.15 on 2026-05-10 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LyricSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('source', models.CharField(default='canonical', max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('changes_requested', 'Changes requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published')], default='draft', max_length=32)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_canonical', models.BooleanField(default=False)),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lyric_sets', to='catalog.track')),
            ],
        ),
        migrations.CreateModel(
            name='LyricSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_ms', models.PositiveIntegerField()),
                ('end_ms', models.PositiveIntegerField()),
                ('text_by_language', models.JSONField(blank=True, default=dict)),
                ('lyric_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='lyrics.lyricset')),
            ],
            options={
                'ordering': ['lyric_set', 'start_ms'],
            },
        ),
        migrations.CreateModel(
            name='LyricLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('original', 'Original'), ('translation', 'Translation'), ('transliteration', 'Transliteration'), ('commentary', 'Commentary')], max_length=32)),
                ('direction', models.CharField(choices=[('ltr', 'Left to right'), ('rtl', 'Right to left')], max_length=8)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('lyric_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='lyrics.lyricset')),
            ],
            options={
                'ordering': ['lyric_set', 'display_order', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='lyricset',
            constraint=models.UniqueConstraint(condition=models.Q(('is_canonical', True)), fields=('track',), name='unique_canonical_lyric_set_per_track'),
        ),
        migrations.AddIndex(
            model_name='lyricsegment',
            index=models.Index(fields=['lyric_set', 'start_ms', 'end_ms'], name='lyrics_lyri_lyric_s_d2f4a9_idx'),
        ),
        migrations.AddConstraint(
            model_name='lyriclanguage',
            constraint=models.UniqueConstraint(fields=('lyric_set', 'code', 'role'), name='unique_lyric_language_role'),
        ),
    ]
