# Generated by Django 5.1.15 on 2026-05-12 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
        ('lyrics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLyricPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible_language_ids', models.JSONField(blank=True, default=list)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lyric_preferences', to='catalog.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lyric_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'track'], name='lyrics_user_user_id_fb87fe_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'track'), name='unique_user_track_lyric_preference')],
            },
        ),
    ]
