# Generated by Django 5.1.15 on 2026-05-10 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('community', '0001_initial'),
        ('lyrics', '0001_initial'),
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_mode', models.CharField(choices=[('audio_visualizer', 'Audio visualizer'), ('video_overlay', 'Video overlay')], max_length=32)),
                ('layout_id', models.CharField(default='landscape-1', max_length=80)),
                ('resolution', models.CharField(choices=[('720p', '720p'), ('1080p', '1080p'), ('4k', '4K')], default='1080p', max_length=16)),
                ('visible_language_ids', models.JSONField(blank=True, default=list)),
                ('title', models.CharField(max_length=240)),
                ('voice', models.CharField(blank=True, max_length=180)),
                ('writer', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=24)),
                ('log', models.TextField(blank=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('lyric_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_generation_jobs', to='lyrics.lyricset')),
                ('output_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_output_jobs', to='media.mediaasset')),
                ('preview_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_preview_jobs', to='media.mediaasset')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='video_generation_jobs', to='media.mediaasset')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_generation_jobs', to='community.submission')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_generation_jobs', to='catalog.track')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='video_gener_status_dc93c1_idx')],
            },
        ),
    ]
