# Generated by Django 5.1.15 on 2026-05-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_generation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogenerationjob',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videogenerationjob',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='videogenerationjob',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videogenerationjob',
            name='render_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
