# Generated by Django 5.1.15 on 2026-06-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='processing_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='processing_error',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='processing_log',
            field=models.TextField(blank=True),
        ),
    ]
