# Generated by Django 5.2.15 on 2026-06-21 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('source_type', models.CharField(choices=[('book', 'Book'), ('manuscript', 'Manuscript'), ('website', 'Website'), ('interview', 'Interview'), ('field_recording', 'Field recording')], max_length=20)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('published_at', models.CharField(blank=True, max_length=60)),
                ('url', models.URLField(blank=True, max_length=1024)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArchiveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visibility', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending review'), ('public', 'Public'), ('unlisted', 'Unlisted'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=16)),
                ('editorial_notes', models.TextField(blank=True)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=320, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('contributor_notes', models.JSONField(blank=True, default=list)),
                ('kalam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_records', to='catalog.kalam')),
                ('related_people', models.ManyToManyField(blank=True, related_name='archive_records', to='catalog.person')),
                ('citations', models.ManyToManyField(blank=True, related_name='records', to='archive.citation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProvenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_name', models.CharField(max_length=200)),
                ('source_url', models.URLField(blank=True, max_length=1024)),
                ('acquired_at', models.DateField(blank=True, null=True)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('note', models.TextField(blank=True)),
                ('archive_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provenance', to='archive.archiverecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SourceRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('editorial', 'Editorial'), ('community', 'Community')], max_length=12)),
                ('value', models.PositiveSmallIntegerField()),
                ('max_value', models.PositiveSmallIntegerField(default=5)),
                ('rationale', models.TextField(blank=True)),
                ('archive_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='archive.archiverecord')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
