# Generated by Django 5.1.15 on 2026-05-10 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archive', '0002_initial'),
        ('catalog', '0002_initial'),
        ('lyrics', '0001_initial'),
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=240)),
                ('voice', models.CharField(blank=True, max_length=180)),
                ('writer', models.CharField(blank=True, max_length=180)),
                ('source_name', models.CharField(blank=True, max_length=240)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('changes_requested', 'Changes requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published')], default='draft', max_length=32)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('citations', models.ManyToManyField(blank=True, related_name='submissions', to='archive.citation')),
                ('lyric_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='lyrics.lyricset')),
                ('media_assets', models.ManyToManyField(blank=True, related_name='submissions', to='media.mediaasset')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
                ('submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CorrectionDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fields', models.JSONField(blank=True, default=list)),
                ('proposed_changes', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('changes_requested', 'Changes requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published')], default='draft', max_length=32)),
                ('target_archive_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correction_drafts', to='archive.archiverecord')),
                ('target_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correction_drafts', to='catalog.track')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_drafts', to='community.submission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=240)),
                ('reciter_name', models.CharField(blank=True, max_length=180)),
                ('writer_name', models.CharField(blank=True, max_length=180)),
                ('source_hint', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('planned', 'Planned'), ('fulfilled', 'Fulfilled'), ('duplicate', 'Duplicate'), ('rejected', 'Rejected')], default='open', max_length=24)),
                ('moderator_note', models.TextField(blank=True)),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='track_requests', to=settings.AUTH_USER_MODEL)),
                ('target_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='track_requests', to='catalog.track')),
            ],
        ),
        migrations.CreateModel(
            name='TrackRequestVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='community.trackrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_request_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.CharField(choices=[('writer', 'Writer'), ('reciter', 'Reciter'), ('lyrics', 'Lyrics'), ('source', 'Source'), ('overall', 'Overall')], max_length=32)),
                ('vote', models.CharField(choices=[('verify', 'Verify'), ('dispute', 'Dispute')], max_length=16)),
                ('note', models.TextField(blank=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_votes', to='community.submission')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status', 'created_at'], name='community_s_status_164170_idx'),
        ),
        migrations.AddIndex(
            model_name='trackrequest',
            index=models.Index(fields=['status', 'created_at'], name='community_t_status_d381da_idx'),
        ),
        migrations.AddConstraint(
            model_name='trackrequestvote',
            constraint=models.UniqueConstraint(fields=('request', 'user'), name='unique_track_request_vote'),
        ),
        migrations.AddConstraint(
            model_name='verificationvote',
            constraint=models.UniqueConstraint(fields=('submission', 'voter', 'field'), name='unique_submission_field_vote'),
        ),
    ]
