# Generated by Django 5.1.15 on 2026-07-04 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_queue_queueitem_saveditem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoGenerationJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_mode",
                    models.CharField(
                        choices=[
                            ("audio_visualizer", "Audio visualizer"),
                            ("video_overlay", "Video overlay"),
                        ],
                        default="audio_visualizer",
                        max_length=24,
                    ),
                ),
                ("layout_id", models.CharField(default="landscape-1", max_length=80)),
                ("resolution", models.CharField(default="1080p", max_length=16)),
                ("visible_language_codes", models.JSONField(blank=True, default=list)),
                ("title", models.CharField(blank=True, max_length=240)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("celery_task_id", models.CharField(blank=True, max_length=120)),
                ("render_payload", models.JSONField(blank=True, default=dict)),
                ("log", models.TextField(blank=True)),
                ("failure_reason", models.TextField(blank=True)),
                ("output_url", models.URLField(blank=True, max_length=1024)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rendition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="video_jobs",
                        to="catalog.rendition",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="video_gener_status_dc93c1_idx",
                    )
                ],
            },
        ),
    ]
