# Generated by Django 5.2.15 on 2026-06-21 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('genre', 'Genre / form'), ('language', 'Language'), ('tradition', 'Tradition / silsila'), ('era', 'Era'), ('theme', 'Theme / occasion'), ('region', 'Region')], max_length=16)),
                ('code', models.SlugField(max_length=80)),
                ('label', models.CharField(max_length=160)),
                ('label_native', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='taxonomy.vocabularyterm')),
            ],
            options={
                'ordering': ['kind', 'label'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'code'), name='unique_term_kind_code')],
            },
        ),
    ]
